import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="w-full">
           <ul className="flex space-x-4 p-4">
            <li>
              <Link href="/" className="text-sinc-50 hover:text-gray-900">
                Home
              </Link>
            </li>
            <li>
              <Link href="/notes" className="text-gray-700 hover:text-gray-900">
                Notes
              </Link>
            </li>
            <li>
              <Link href="/about" className="text-gray-700 hover:text-gray-900">
                About
              </Link>
            </li>
           </ul>
        </nav>
        {children}
        <footer className="w-full p-4 text-center text-gray-500">
          &copy; 2023 My App. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
